- // MIR for `forget` before LowerIntrinsics
+ // MIR for `forget` after LowerIntrinsics
  
  fn forget(_1: T) -> () {
      debug t => _1;
      let mut _0: ();
      let mut _2: T;
  
      bb0: {
          StorageLive(_2);
          _2 = move _1;
-         _0 = std::intrinsics::forget::<T>(Spanned { node: move _2, span: $DIR/lower_intrinsics.rs:37:30: 37:31 (#0) }) -> [return: bb1, unwind unreachable];
+         _0 = const ();
+         goto -> bb1;
      }
  
      bb1: {
          StorageDead(_2);
          goto -> bb2;
      }
  
      bb2: {
          return;
      }
  }
  
