- // MIR for `read_via_copy_uninhabited` before LowerIntrinsics
+ // MIR for `read_via_copy_uninhabited` after LowerIntrinsics
  
  fn read_via_copy_uninhabited(_1: &Never) -> Never {
      debug r => _1;
      let mut _0: Never;
      let mut _2: *const Never;
      scope 1 {
      }
  
      bb0: {
          StorageLive(_2);
          _2 = &raw const (*_1);
-         _0 = read_via_copy::<Never>(Spanned { node: move _2, span: $DIR/lower_intrinsics.rs:135:46: 135:47 (#0) }) -> unwind unreachable;
+         _0 = (*_2);
+         unreachable;
      }
  }
  
